---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-cluster1-default.cluster-cvrbmcz1xxrq.eu-central-1.rds.amazonaws.com
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: user
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
