ARG ELK_VERSION

# httpswww.docker.elastic.co
FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

# Add your logstash plugins setup here
# Example RUN logstash-plugin install logstash-filter-json