apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace}}
  name: {{ .Values.deployment.backend.name }}
spec:
  selector:
    app: {{ .Values.deployment.backend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.deployment.backend.service.port }}
      targetPort: {{ .Values.deployment.backend.service.port }}

