apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.statefulset.name }}
spec:
  selector:
    app: {{ .Values.statefulset.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.statefulset.service.port }}
      targetPort: {{ .Values.statefulset.service.port }}

