---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-nginx-template
data:
  nginx.conf.tmpl: |
    worker_processes     4;
    worker_rlimit_nofile 65535;
    pid /tmp/nginx.pid;


    events {
        multi_accept       on;
        worker_connections 65535;
    }

    http {
        charset                utf-8;
        sendfile               on;
        tcp_nopush             on;
        tcp_nodelay            on;
        server_tokens          off;
        log_not_found          off;
        types_hash_max_size    2048;
        types_hash_bucket_size 64;
        client_max_body_size   16M;


        # Logging
        access_log             /var/log/nginx/access.log;
        error_log              /var/log/nginx/error.log warn;

        server {
            listen 8080;
            client_body_temp_path /tmp/client_temp;
            proxy_temp_path /tmp/proxy_temp;
            fastcgi_temp_path /tmp/fastcgi_temp;
            uwsgi_temp_path /tmp/uwsgi_temp;
            scgi_temp_path /tmp/scgi_temp;

            location / {
              {{ with secret "secret/fedora/secretkey" }}
              return 200 '{{ .Data.data.responseText }}';
              add_header Content-Type text/plain always;
              {{ end }}
            }
            }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-configs
data:
  vault-agent-init.hcl: |
    pid_file = "/tmp/.pidfile"

    auto_auth {
      mount_path = "auth/approle"
      method "approle" {
        config = {
          role_id_file_path = "/etc/vault/config/app-role-id"
        }
      }
    }
    template {
                source      = "/etc/vault/config/template/nginx/nginx.conf.tmpl"
                destination = "/etc/vault/config/render/nginx/nginx.conf"
    }

    vault {
      address = "http://vault:8200"
    }
    exit_after_auth = true
  vault-agent-reload.hcl: |
    pid_file = "/tmp/.pidfile"

    auto_auth {
      mount_path = "auth/approle"
      method "approle" {
        config = {
          role_id_file_path = "/etc/vault/config/app-role-id"
        }
      }
    }

    template {
          source      = "/etc/vault/config/template/nginx/nginx.conf.tmpl"
          destination = "/etc/vault/config/render/nginx/nginx.conf"
          command = "ps ax | grep 'nginx: maste[r]' | awk '{print $1}' | xargs kill -s HUP"
    }
    template_config {
          static_secret_render_interval = "1m"
    }

    vault {
      address = "http://vault:8200"
    }

  app-role-id: |
    cc7a11b1-2f31-0b9e-aaec-327052a5919c