---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-autoreload
  labels:
    role: nginx-reload-test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      role: nginx-reload-test
  template:
    metadata:
      labels:
        role: nginx-reload-test
    spec:
      shareProcessNamespace: true
      initContainers:
        - name: init-nginx-config
          image: vault:1.9.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 10001
            runAsNonRoot: true
            capabilities:
              add:
                - IPC_LOCK
          args:
            - "agent"
            - "-config=/etc/vault/config/vault-agent-init.hcl"
          env:
            - name: SKIP_SETCAP
              value: 'true'
          volumeMounts:
            - mountPath: /etc/vault/config
              name: vault-agent-config
            - mountPath: /etc/vault/config/template/nginx
              name: vault-nginx-template
            - mountPath: /etc/vault/config/render/nginx
              name: nginx-rendered-conf
      containers:
        - name: nginx
          image: nginx:1.21.4-alpine
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/nginx/
              name: nginx-rendered-conf
              readOnly: true
          resources:
            requests:
              cpu: "0.2"
              memory: "200Mi"
            limits:
              cpu: "0.5"
              memory: "500Mi"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          securityContext:
            runAsUser: 10001
            runAsNonRoot: true
        - name: vault-agent-rerender
          image: vault:1.9.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 10001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - IPC_LOCK
                - SYS_PTRACE
          args:
            - "agent"
            - "-config=/etc/vault/config/vault-agent-reload.hcl"
          env:
            - name: SKIP_SETCAP
              value: 'true'
          volumeMounts:
            - mountPath: /etc/vault/config
              name: vault-agent-config
            - mountPath: /etc/vault/config/template/nginx
              name: vault-nginx-template
            - mountPath: /etc/vault/config/render/nginx
              name: nginx-rendered-conf
      volumes:
        - name: vault-nginx-template
          configMap:
            name: vault-nginx-template
        - name: vault-agent-config
          configMap:
            name: vault-agent-configs
        - name: nginx-rendered-conf
          emptyDir:
            medium: Memory
