---
# tasks file for hello-world-role
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: hello-world
        namespace: default
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: hello-world
        template:
          metadata:
            labels:
              app: hello-world
          spec:
            containers:
            - image: k8s.gcr.io/echoserver:1.4 
              # Имидж взял другой, что бы не загружать еще один мусор в репозиторий- name: Hello World role
              name: hello-world
                
                
