{
 "title": "Netology",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Home Work 10.3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Free disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\",fstype!=\"tmpfs\"}/1024^3"
    }
   ]
  },
  {
   "title": "CPU utilazation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{instance=\"nodeexporter:9100\", job=\"nodeexporter\", mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"} / (node_memory_MemTotal_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"} / 100)"
    }
   ]
  },
  {
   "title": "CPU LA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}) / count(count(node_cpu_seconds_total{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}) by (cpu)) * 100"
    },
    {
     "expr": "avg(node_load5{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}) / count(count(node_cpu_seconds_total{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}) by (cpu)) * 100"
    },
    {
     "expr": "avg(node_load15{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}) / count(count(node_cpu_seconds_total{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}) by (cpu)) * 100"
    }
   ]
  }
 ]
}