---
- name: Install cluster node
  hosts: "127.0.0.1"
  connection: local
  gather_facts: False
  vars_files:
    - keys/aws_credentials.yml
  tasks:
    - name: Launch Cluster Node in AWS cloud
      ec2_instance:
        instance_type: t3.small
        image_id: ami-05f7491af5eef733a
        region: eu-central-1
        wait: yes
        state: present
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        key_name: "{{ aws_keypair }}"
        tags: {"Name": "Minicube", "Cluster": "k8s cluster"}
      register: ec2

    - debug: var=ec2
    - debug: var={{ item }}
      with_items: "{{ ec2.instances }}"

    - add_host: hostname={{ item.public_ip_address }} groupname=ec2hosts
      with_items: "{{ ec2.instances }}"

    - name: wait for instances to listen on port:22
      wait_for:
        state=started
        host={{ item.public_dns_name }}
        port=22
      with_items: "{{ ec2.instances }}"

- name: Install k8s with Hello World role
  hosts: ec2hosts
  roles:
    - minikube-role
    - hello-world-role



